// <auto-generated />
using System;
using FiapCloudGames.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FiapCloudGames.API.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250621183603_seed_admin_user")]
    partial class seed_admin_user
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FiapCloudGames.API.Modules.Games.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Price")
                        .HasPrecision(8, 2)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("FiapCloudGames.API.Modules.Roles.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1bd7d258-b3fd-4e95-985f-811173518b30"),
                            CreatedAt = new DateTime(2025, 6, 21, 18, 36, 2, 264, DateTimeKind.Utc).AddTicks(9212),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("93f46947-3ff4-4ed2-a3eb-4fcec16014eb"),
                            CreatedAt = new DateTime(2025, 6, 21, 18, 36, 2, 264, DateTimeKind.Utc).AddTicks(9225),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("FiapCloudGames.API.Modules.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("440f02c7-1a65-4d78-a688-2d761373bad1"),
                            CreatedAt = new DateTime(2025, 6, 21, 18, 36, 2, 265, DateTimeKind.Utc).AddTicks(2572),
                            Email = "admin@fcg.com",
                            Name = "Admin",
                            Password = "$2a$11$W8znD/qgMC7JK4OVRBgRcezlrEaSjIe3ycxLH/byk.rAflMmndqgG",
                            RoleId = new Guid("1bd7d258-b3fd-4e95-985f-811173518b30")
                        });
                });

            modelBuilder.Entity("FiapCloudGames.API.Modules.Users.Entities.User", b =>
                {
                    b.HasOne("FiapCloudGames.API.Modules.Roles.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FiapCloudGames.API.Modules.Roles.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
